// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAppliance = "appliance"

// Appliance mapped from table <appliance>
type Appliance struct {
	ID   int32  `gorm:"column:id;primaryKey" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
	URL  string `gorm:"column:url;not null" json:"url"`
}

// TableName Appliance's table name
func (*Appliance) TableName() string {
	return TableNameAppliance
}
